services:
  react-deno-starter:
    image: react-deno-starter:0.1.0
    container_name: react-deno-starter
    ports:
      - 80:80
    environment:
      - VITE_API_URL=https://app2.demo.com/graphql
